let options = {
  flipped: false,
  random: false,
};

//el  orden de los objetos es como apareceran en la pagina
const lectures = [
  {
    id: "3",
    name: "Leccion 1 Minna",
    termList: [
      { id: 0, term: "わたし", extra: "私", answer: "Yo" },
      { id: 1, term: "わたしたち", extra: "私達", answer: "Nosotros" },
      { id: 2, term: "あなた", extra: "", answer: "Usted" },
      { id: 3, term: "あのひと", extra: "あの人", answer: "Aquella persona" },
      {
        id: 4,
        term: "あのかた",
        extra: "あの方",
        answer: "Aquella persona(formal)",
      },
      { id: 5, term: "みなさん", extra: "皆さん", answer: "Todos" },
      { id: 6, term: "さん", extra: "", answer: "Señor" },
      {
        id: 7,
        term: "ちゃん",
        extra: "",
        answer: "Sufijo antiguamente para niñas pero hoy en dia cualquier sexo",
      },
      {
        id: 8,
        term: "くん",
        extra: "",
        answer: "Sufijo antiguamente para niños pero hoy en dia cualquier sexo",
      },
      { id: 9, term: "じん", extra: "人", answer: "Sufijo nacionalidad" },
      {
        id: 10,
        term: "せんせい",
        extra: "先生",
        answer: "Profesor(para llamar atencion del profesor)",
      },
      {
        id: 11,
        term: "きょうし",
        extra: "教師",
        answer: "Profesor(profesion, cuando te refieres a ti mismo)",
      },
      {
        id: 12,
        term: "がくせい",
        extra: "学生",
        answer: "Estudiante(cuando te refieres a ti mismo)",
      },
      {
        id: 45,
        term: "せいと",
        extra: "生徒",
        answer: "Estudiante(para llamar la atencion del estudiante)",
      },
      {
        id: 13,
        term: "かいしゃいん",
        extra: "会社員",
        answer: "Empleado de una empresa",
      },
      {
        id: 14,
        term: "しゃいん",
        extra: "社員",
        answer: "Empleado de la empresa",
      },
      {
        id: 15,
        term: "ぎんこういん",
        extra: "銀行員",
        answer: "Empleado de banco",
      },
      { id: 16, term: "いしゃ", extra: "医者", answer: "Doctor" },
      {
        id: 17,
        term: "けんきゅうしゃ",
        extra: "研究者",
        answer: "Investigador",
      },
      { id: 18, term: "エンジニア", extra: "", answer: "Ingeniero" },
      { id: 19, term: "だいがく", extra: "大学", answer: "Universidad" },
      { id: 20, term: "びょういん", extra: "病院", answer: "Hospital" },
      { id: 21, term: "でんき", extra: "電気", answer: "Electricidad" },
      { id: 22, term: "だれ", extra: "誰", answer: "Quien" },
      { id: 23, term: "どなた", extra: "", answer: "Quien(formal)" },
      { id: 24, term: "さい", extra: "歳 / 才", answer: "Contador edad" },
      { id: 25, term: "なんさい", extra: "何歳", answer: "Cuantos años" },
      { id: 26, term: "おいくつ", extra: "お幾つ", answer: "Que edad(formal)" },
      { id: 27, term: "はい", extra: "", answer: "Si" },
      { id: 28, term: "いいえ", extra: "", answer: "No" },
      {
        id: 29,
        term: "しつれいですが",
        extra: "失礼ですが",
        answer: "Disculpe pero",
      },
      {
        id: 30,
        term: "おなまえは？",
        extra: "お名前は",
        answer: "Como se llama usted?",
      },
      {
        id: 31,
        term: "はじめまして",
        extra: "初めまして",
        answer: "Mucho gusto",
      },
      {
        id: 32,
        term: "どうぞよろしく",
        extra: "",
        answer: "Encantado de conocerte",
      },
      {
        id: 33,
        term: "こちらは。。。さんです",
        extra: "",
        answer: "Le presento a...",
      },
      { id: 34, term: "。。。からきました", extra: "", answer: "Vengo de..." },
      { id: 35, term: "アメリカ", extra: "", answer: "EE.UU" },
      { id: 36, term: "イギリス", extra: "", answer: "Inglaterra" },
      { id: 37, term: "インド", extra: "", answer: "India" },
      { id: 38, term: "インドネシア", extra: "", answer: "Indonesia" },
      { id: 39, term: "かんこく", extra: "韓国", answer: "Corea del sur" },
      { id: 40, term: "タイ", extra: "", answer: "Tailandia" },
      { id: 41, term: "ちゅうごく", extra: "中国", answer: "China" },
      { id: 42, term: "ドイツ", extra: "", answer: "Alemania" },
      { id: 43, term: "にほん", extra: "日本", answer: "Japon" },
      { id: 44, term: "フランス", extra: "", answer: "Francia" },
    ],
  },
  {
    id: "4",
    name: "Clase 1",
    termList: [
      { id: 0, term: "せつめい", extra: "説明", answer: "Explicacion" },
      { id: 1, term: "ないよう", extra: "内容", answer: "Contenido, Detalle" },
      {
        id: 2,
        term: "きめます、きめる",
        extra: "決める",
        answer: "Decidir",
      },
      {
        id: 69,
        term: "えらびます、えらぶ",
        extra: "選ぶ",
        answer: "Elegir",
      },
      { id: 3, term: "じゅぎょう", extra: "授業", answer: "Clase" },
      { id: 4, term: "かいわ", extra: "会話", answer: "Conversacion" },
      { id: 5, term: "ふくしゅう", extra: "復習", answer: "Repaso" },
      { id: 6, term: "か", extra: "課", answer: "Contador leccion" },
      { id: 7, term: "ほんもの", extra: "本物", answer: "Real, Autentico" },
      { id: 8, term: "にんき", extra: "人気", answer: "Popular" },
      { id: 9, term: "ぐ", extra: "具", answer: "Relleno/Ingrediente" },
      {
        id: 10,
        term: "ざいりょう",
        extra: "材料",
        answer: "Material/Materiales",
      },
      {
        id: 11,
        term: "ぐざい",
        extra: "具材",
        answer:
          "Ingrediente(Carne, pescado y verduras para añadir a sopas, guisos, etc.)",
      },
      {
        id: 12,
        term: "しょくざい",
        extra: "食材",
        answer:
          "Ingrediente(Carne, pescado y verduras en general utilizados en la cocina.)",
      },
      {
        id: 13,
        term: "ようい",
        extra: "用意",
        answer:
          "Preparacion(Cuando lo que hay que preparar es formulista o específico.)",
      },
      {
        id: 14,
        term: "よういする、よういします",
        extra: "用意する",
        answer: "Preparar",
      },
      {
        id: 15,
        term: "じゅんび",
        extra: "準備",
        answer:
          "Preparacion(Puede ser más amplio e incluir posturas distintas de los objetos)",
      },
      {
        id: 16,
        term: "じゅんびする、じゅんびします",
        extra: "準備する",
        answer: "Preparar",
      },
      {
        id: 17,
        term: "おいはらう、おいはらいます",
        extra: "追い払う",
        answer: "Alejarse",
      },
      {
        id: 18,
        term: "は/はっぱ",
        extra: "葉/葉っぱ",
        answer: "Hoja(s) de arbol o flor",
      },
      { id: 19, term: "ふじん", extra: "婦人", answer: "Señora(s)" },
      { id: 20, term: "しゃかい", extra: "社会", answer: "Sociedad" },
      {
        id: 21,
        term: "かつやく",
        extra: "活躍",
        answer: "Participacion activa",
      },
      { id: 22, term: "さんか", extra: "参加", answer: "Participacion" },
      {
        id: 23,
        term: "さんかする、さんかします",
        extra: "参加する",
        answer: "Participar",
      },
      { id: 24, term: "けんり", extra: "権利", answer: "Derechos" },
      {
        id: 25,
        term: "とうひょうけん",
        extra: "投票権",
        answer: "Derecho de voto",
      },
      { id: 26, term: "おくる、おくります", extra: "贈る", answer: "Regalar" },
      {
        id: 27,
        term: "れんしゅう",
        extra: "練習",
        answer: "Practica, Entrenamiento",
      },
      {
        id: 28,
        term: "りゆう",
        extra: "理由",
        answer: "Razon, Pretexto, Motivo",
      },
      { id: 29, term: "ぜんぶ", extra: "全部", answer: "Todo" },
      { id: 30, term: "つかいます、つかう", extra: "使う", answer: "Usar" },
      {
        id: 31,
        term: "ならいます、ならう",
        extra: "習う",
        answer: "Aprender(de un profesor), Tomar clases en",
      },
      {
        id: 32,
        term: "かんじ",
        extra: "漢字",
        answer: "Kanji, Caracter chino",
      },
      { id: 33, term: "よみます、よむ", extra: "読む", answer: "Leer" },
      {
        id: 34,
        term: "〜かた",
        extra: "〜方",
        answer: "Direccion, Persona, Manera",
      },
      {
        id: 35,
        term: "なおします、なおす",
        extra: "直す",
        answer: "Reparar, Arreglar, Corregir",
      },
      {
        id: 36,
        term: "はなします、はなす",
        extra: "話す",
        answer: "Hablar, Decir",
      },
      { id: 37, term: "かきます、かく", extra: "書く", answer: "Escribir " },
      {
        id: 38,
        term: "かきます、かく",
        extra: "描く",
        answer: "Dibujar, Pintar",
      },
      { id: 39, term: "みじかい", extra: "短い", answer: "Corto" },
      {
        id: 40,
        term: "かんがえます、かんがえる",
        extra: "考える",
        answer: "Pensar, Contemplar, Meditar",
      },
      { id: 41, term: "しゃしん", extra: "写真", answer: "Foto" },
      { id: 42, term: "ろう", extra: "蝋", answer: "Cera" },
      { id: 43, term: "ロウソク/キャンドル", extra: "", answer: "Vela" },
      { id: 44, term: "ひつよう", extra: "必要", answer: "Necesario" },
      {
        id: 45,
        term: "ぜったいにひつよう",
        extra: "ぜったいに必要",
        answer: "No puede faltar, Debe tener",
      },
      {
        id: 46,
        term: "あまずっぱい",
        extra: "甘酸っぱい",
        answer: "Agridulce",
      },
      { id: 47, term: "す", extra: "酢", answer: "Vinagre" },
      { id: 48, term: "はんぶん", extra: "半分", answer: "Mitad" },
      { id: 49, term: "やさい", extra: "野菜", answer: "Vegetal" },
      {
        id: 50,
        term: "たまごやき",
        extra: "卵焼き",
        answer: "Tamagoyaki, Omelette japones",
      },
      {
        id: 51,
        term: "とります、とる",
        extra: "取る",
        answer: "Sacar, Remover",
      },
      {
        id: 52,
        term: "せわた",
        extra: "背わた",
        answer: "Tracto digestivo del camaron",
      },
      {
        id: 53,
        term: "のせます、のせる",
        extra: "乗せる",
        answer: "Poner algo en (algo)",
      },
      { id: 54, term: "さいご", extra: "最後", answer: "Final, Conclusion" },
      { id: 55, term: "かたち", extra: "形", answer: "Forma, Figura" },
      {
        id: 56,
        term: "まきます、まく",
        extra: "巻く",
        answer: "Enrollar, Envolver",
      },
      { id: 57, term: "おまつり", extra: "お祭り", answer: "Festival" },
      { id: 58, term: "にんぎょう", extra: "人形", answer: "Muñeca" },
      { id: 59, term: "とくべつ", extra: "特別", answer: "Especial" },
      { id: 60, term: "かざり", extra: "", answer: "Decoracion" },
      { id: 61, term: "けんこう", extra: "", answer: "Salud" },
      {
        id: 62,
        term: "しあわせ",
        extra: "幸せ",
        answer: "Felicidad, Buena suerte",
      },
      { id: 63, term: "いのります、いのる", extra: "祈る", answer: "Rezar" },
      { id: 64, term: "きせつ", extra: "季節", answer: "Estacion(del año)" },
      { id: 65, term: "もも", extra: "桃", answer: "Durazno" },
      { id: 66, term: "はだ", extra: "肌", answer: "Piel" },
      {
        id: 67,
        term: "おふろ",
        extra: "お風呂",
        answer: "Ducha, Duchar, Lugar de ducha",
      },
      { id: 68, term: "よくそう", extra: "浴槽", answer: "Bañera" },
    ],
  },
  {
    id: "5",
    name: "Clase 1 Kanji",
    termList: [
      { id: 0, term: "説明", extra: "", answer: "せつめい / Explicacion" },
      {
        id: 1,
        term: "内容",
        extra: "",
        answer: "ないよう / Contenido, Detalle",
      },
      {
        id: 2,
        term: "決める",
        extra: "",
        answer: "きめます、きめる / Decidir",
      },
      {
        id: 66,
        term: "選ぶ",
        extra: "",
        answer: "えらびます、えらぶ / Elegir",
      },
      { id: 3, term: "授業", extra: "", answer: "じゅぎょう / Clase" },
      { id: 4, term: "会話", extra: "", answer: "かいわ / Conversacion" },
      { id: 5, term: "復習", extra: "", answer: "ふくしゅう / Repaso" },
      { id: 6, term: "課", extra: "", answer: "か / Contador leccion" },
      { id: 7, term: "本物", extra: "", answer: "ほんもの / Real, Autentico" },
      { id: 8, term: "人気", extra: "", answer: "にんき / Popular" },
      { id: 9, term: "具", extra: "", answer: "ぐ / Relleno/Ingrediente" },
      {
        id: 10,
        term: "材料",
        extra: "",
        answer: "ざいりょう / Material/Materiales",
      },
      {
        id: 11,
        term: "具材",
        extra: "",
        answer:
          "ぐざい / Ingrediente(Carne, pescado y verduras para añadir a sopas, guisos, etc.)",
      },
      {
        id: 12,
        term: "食材",
        extra: "",
        answer:
          "しょくざい / Ingrediente(Carne, pescado y verduras en general utilizados en la cocina.)",
      },
      {
        id: 13,
        term: "用意",
        extra: "",
        answer:
          "ようい / Preparacion(Cuando lo que hay que preparar es formulista o específico.)",
      },
      {
        id: 15,
        term: "準備",
        extra: "",
        answer:
          "じゅんび / Preparacion(Puede ser más amplio e incluir posturas distintas de los objetos)",
      },
      {
        id: 17,
        term: "追い払う",
        extra: "",
        answer: "おいはらう、おいはらいます / Alejarse",
      },
      {
        id: 18,
        term: "葉/葉っぱ",
        extra: "",
        answer: "は/はっぱ / Hoja(s) de arbol o flor",
      },
      { id: 19, term: "婦人", extra: "", answer: "ふじん / Señora(s)" },
      { id: 20, term: "社会", extra: "", answer: "しゃかい / Sociedad" },
      {
        id: 21,
        term: "活躍",
        extra: "",
        answer: "かつやく / Participacion activa",
      },
      { id: 22, term: "参加", extra: "", answer: "さんか / Participacion" },
      { id: 24, term: "権利", extra: "", answer: "けんり / Derechos" },
      {
        id: 25,
        term: "投票権",
        extra: "",
        answer: "とうひょうけん / Derecho de voto",
      },
      {
        id: 26,
        term: "贈る",
        extra: "",
        answer: "おくる、おくります / Regalar",
      },
      {
        id: 27,
        term: "練習",
        extra: "",
        answer: "れんしゅう / Practica, Entrenamiento",
      },
      {
        id: 28,
        term: "理由",
        extra: "",
        answer: "りゆう / Razon, Pretexto, Motivo",
      },
      { id: 29, term: "全部", extra: "", answer: "ぜんぶ / Todo" },
      { id: 30, term: "使う", extra: "", answer: "つかいます、つかう / Usar" },
      {
        id: 31,
        term: "習う",
        extra: "",
        answer:
          "ならいます、ならう / Aprender(de un profesor), Tomar clases en",
      },
      {
        id: 32,
        term: "漢字",
        extra: "",
        answer: "かんじ / Kanji, Caracter chino",
      },
      { id: 33, term: "読む", extra: "", answer: "よみます、よむ / Leer" },
      {
        id: 34,
        term: "〜方",
        extra: "",
        answer: "〜かた / Direccion, Persona, Manera",
      },
      {
        id: 35,
        term: "直す",
        extra: "",
        answer: "なおします、なおす / Reparar, Arreglar, Corregir",
      },
      {
        id: 36,
        term: "話す",
        extra: "",
        answer: "はなします、はなす / Hablar, Decir",
      },
      { id: 37, term: "書く", extra: "", answer: "かきます、かく / Escribir " },
      {
        id: 38,
        term: "描く",
        extra: "",
        answer: "かきます、かく / Dibujar, Pintar",
      },
      { id: 39, term: "短い", extra: "", answer: "みじかい / Corto" },
      {
        id: 40,
        term: "考える",
        extra: "",
        answer: "かんがえます、かんがえる / Pensar, Contemplar, Meditar",
      },
      { id: 41, term: "写真", extra: "", answer: "しゃしん / Foto" },
      { id: 42, term: "蝋", extra: "", answer: "ろう / Cera" },
      { id: 43, term: "必要", extra: "", answer: "ひつよう / Necesario" },
      {
        id: 45,
        term: "甘酸っぱい",
        extra: "",
        answer: "あまずっぱい / Agridulce",
      },
      { id: 46, term: "酢", extra: "", answer: "す / Vinagre" },
      { id: 47, term: "半分", extra: "", answer: "はんぶん / Mitad" },
      { id: 48, term: "野菜", extra: "", answer: "やさい / Vegetal" },
      {
        id: 49,
        term: "卵焼き",
        extra: "",
        answer: "たまごやき / Tamagoyaki, Omelette japones",
      },
      {
        id: 50,
        term: "取る",
        extra: "",
        answer: "とります、とる / Sacar, Remover",
      },
      {
        id: 51,
        term: "背わた",
        extra: "",
        answer: "せわた / Tracto digestivo del camaron",
      },
      {
        id: 52,
        term: "乗せる",
        extra: "",
        answer: "のせます、のせる / Poner algo en (algo)",
      },
      { id: 53, term: "最後", extra: "", answer: "さいご / Final, Conclusion" },
      { id: 54, term: "形", extra: "", answer: "かたち / Forma, Figura" },
      {
        id: 55,
        term: "巻く",
        extra: "",
        answer: "まきます、まく / Enrollar, Envolver",
      },
      { id: 56, term: "お祭り", extra: "", answer: "おまつり / Festival" },
      { id: 57, term: "人形", extra: "", answer: "にんぎょう / Muñeca" },
      { id: 58, term: "特別", extra: "", answer: "とくべつ / Especial" },
      {
        id: 59,
        term: "幸せ",
        extra: "",
        answer: "しあわせ / Felicidad, Buena suerte",
      },
      { id: 60, term: "祈る", extra: "", answer: "いのります、いのる / Rezar" },
      { id: 61, term: "季節", extra: "", answer: "きせつ / Estacion(del año)" },
      { id: 62, term: "桃", extra: "", answer: "もも / Durazno" },
      { id: 63, term: "肌", extra: "", answer: "はだ / Piel" },
      {
        id: 64,
        term: "お風呂",
        extra: "",
        answer: "おふろ / Ducha, Duchar, Lugar de ducha",
      },
      { id: 65, term: "浴槽", extra: "", answer: "よくそう / Bañera" },
    ],
  },
  {
    id: "6",
    name: "Clase 1 Extra",
    termList: [
      { id: 0, term: "こくさい", extra: "国際", answer: "Internacional" },
      {
        id: 1,
        term: "じょせい",
        extra: "女性",
        answer: "Mujer, Genero Femenino, (formal)",
      },
      {
        id: 2,
        term: "だんせい",
        extra: "男性",
        answer: "Hombre, Genero Masculino, (formal)",
      },
      { id: 3, term: "おおい", extra: "多い", answer: "Muchos, Numeroso" },
      {
        id: 4,
        term: "すすみます、すすむ",
        extra: "進む",
        answer: "Progresar, Avanzar",
      },
      {
        id: 5,
        term: "きょういく",
        extra: "教育",
        answer: "Educacion, Entrenamiento",
      },
      { id: 6, term: "うけます、うける", extra: "受ける", answer: "Recibir" },
      {
        id: 7,
        term: "あるべき",
        extra: "有るべき",
        answer: "Ideal, Deseable, La forma que algo deberia ser",
      },
      {
        id: 8,
        term: "ふえます、ふえる",
        extra: "増える",
        answer: "Incrementar, Multiplicar",
      },
      { id: 9, term: "ねん", extra: "年", answer: "Año" },
      {
        id: 10,
        term: "せかい",
        extra: "世界",
        answer: "El mundo, Sociedad, El Universo",
      },
      { id: 11, term: "はじめて", extra: "初めて", answer: "Por primera vez" },
      { id: 12, term: "せいじ", extra: "政治", answer: "Politica, Gobierno" },
      {
        id: 13,
        term: "みとめます、みとめる",
        extra: "認める",
        answer: "Permitir, Aprovar",
      },
      { id: 14, term: "だいとうりょう", extra: "大統領", answer: "Presidente" },
      { id: 15, term: "しゅじん", extra: "主人", answer: "Esposo, Dueño" },
      { id: 16, term: "かない", extra: "家内", answer: "Esposa" },
      { id: 17, term: "あと", extra: "後", answer: "Atras, Despues" },
      { id: 18, term: "ようやく", extra: "漸く", answer: "Finalmente" },
      { id: 19, term: "くにぐに", extra: "国々", answer: "Paises" },
      {
        id: 20,
        term: "あつまります、あつまる",
        extra: "集まる",
        answer: "Juntarse",
      },
      { id: 21, term: "やくそく", extra: "約束", answer: "Promesa, Cita" },
      { id: 22, term: "やくそくする", extra: "約束する", answer: "Prometer" },
      { id: 23, term: "だい", extra: "第", answer: "Prefijo numero ordinal" },
      { id: 24, term: "しょう", extra: "賞", answer: "Premio" },
      {
        id: 25,
        term: "とくに",
        extra: "特に",
        answer: "En particular..., En especial...",
      },
      { id: 26, term: "しき", extra: "式", answer: "Ceremonia" },
      {
        id: 27,
        term: "おこなう",
        extra: "行う",
        answer: "Llevar a cabo, Hacer",
      },
      { id: 28, term: "えいが", extra: "映画", answer: "Pelicula" },
      {
        id: 29,
        term: "げんざい",
        extra: "現在",
        answer: "Ahora(solo ocupado en escritura)",
      },
      { id: 30, term: "さいご", extra: "最後", answer: "Ultimo" },
      { id: 31, term: "さいしょ", extra: "最初", answer: "Primero" },
    ],
  },
  {
    id: "7",
    name: "Clase 1 Extra Kanji",
    termList: [
      { id: 0, term: "国際", extra: "", answer: "こくさい / Internacional" },
      {
        id: 1,
        term: "女性",
        extra: "",
        answer: "じょせい / Mujer, Genero Femenino, (formal)",
      },
      {
        id: 2,
        term: "男性",
        extra: "",
        answer: "だんせい / Hombre, Genero Masculino, (formal)",
      },
      { id: 3, term: "多い", extra: "", answer: "おおい / Muchos, Numeroso" },
      {
        id: 4,
        term: "進む",
        extra: "",
        answer: "すすみます、すすむ / Progresar, Avanzar",
      },
      {
        id: 5,
        term: "教育",
        extra: "",
        answer: "きょういく / Educacion, Entrenamiento",
      },
      {
        id: 6,
        term: "受ける",
        extra: "",
        answer: "うけます、うける / Recibir",
      },
      {
        id: 7,
        term: "有るべき",
        extra: "",
        answer: "あるべき / Ideal, Deseable, La forma que algo deberia ser",
      },
      {
        id: 8,
        term: "増える",
        extra: "",
        answer: "ふえます、ふえる / Incrementar, Multiplicar",
      },
      { id: 9, term: "年", extra: "", answer: "ねん / Año" },
      {
        id: 10,
        term: "世界",
        extra: "",
        answer: "せかい / El mundo, Sociedad, El Universo",
      },
      {
        id: 11,
        term: "初めて",
        extra: "",
        answer: "はじめて / Por primera vez",
      },
      {
        id: 12,
        term: "政治",
        extra: "",
        answer: "せいじ / Politica, Gobierno",
      },
      {
        id: 13,
        term: "認める",
        extra: "",
        answer: "みとめます、みとめる / Permitir, Aprovar",
      },
      {
        id: 14,
        term: "大統領",
        extra: "",
        answer: "だいとうりょう / Presidente",
      },
      { id: 15, term: "主人", extra: "", answer: "しゅじん / Esposo, Dueño" },
      { id: 16, term: "家内", extra: "", answer: "かない / Esposa" },
      { id: 17, term: "後", extra: "", answer: "あと / Atras, Despues" },
      { id: 18, term: "漸く", extra: "", answer: "ようやく / Finalmente" },
      { id: 19, term: "国々", extra: "", answer: "くにぐに / Paises" },
      {
        id: 20,
        term: "集まる",
        extra: "",
        answer: "あつまります、あつまる / Juntarse",
      },
      { id: 21, term: "約束", extra: "", answer: "やくそく / Promesa, Cita" },
      {
        id: 22,
        term: "約束する",
        extra: "",
        answer: "やくそくする / Prometer",
      },
      {
        id: 23,
        term: "第",
        extra: "",
        answer: "だい / Prefijo numero ordinal",
      },
      { id: 24, term: "賞", extra: "", answer: "しょう / Premio" },
      {
        id: 25,
        term: "特に",
        extra: "",
        answer: "とくに / En particular..., En especial...",
      },
      { id: 26, term: "式", extra: "", answer: "しき / Ceremonia" },
      {
        id: 27,
        term: "行う",
        extra: "",
        answer: "おこなう / Llevar a cabo, Hacer",
      },
      { id: 28, term: "映画", extra: "", answer: "えいが / Pelicula" },
      {
        id: 29,
        term: "現在",
        extra: "",
        answer: "げんざい / Ahora(solo se usa en escritura)",
      },
      { id: 30, term: "最後", extra: "", answer: "さいご / Ultimo" },
      { id: 31, term: "最初", extra: "", answer: "さいしょ / Primero" },
    ],
  },
  {
    id: "8",
    name: "Clase 2",
    termList: [
      {
        id: 0,
        term: "じこしょうかい",
        extra: "自己紹介",
        answer: "Presentarse a si mismo",
      },
      { id: 1, term: "かきじゅん", extra: "書き順", answer: "Orden de trazos" },
      {
        id: 2,
        term: "おとこ",
        extra: "漢",
        answer: "Hombre de hombres, Macho, Tipo duro.",
      },
      {
        id: 3,
        term: "じょし",
        extra: "女子",
        answer: "Mujer, Niña, (hasta 18 años)",
      },
      {
        id: 4,
        term: "だんし",
        extra: "男子",
        answer: "Hombre, Niño, (hasta 18 años)",
      },
      { id: 5, term: "もじ", extra: "文字", answer: "Letra" },
      { id: 6, term: "ぶん", extra: "文", answer: "Oracion" },
      {
        id: 7,
        term: "ぶんしょう",
        extra: "文章",
        answer: "Ensayo（escrito）, Oraciones",
      },
      { id: 8, term: "ぶんか", extra: "文化", answer: "Cultura" },
      { id: 9, term: "こうがく", extra: "工学", answer: "Ingenieria" },
      { id: 10, term: "やど", extra: "宿", answer: "Alojamiento, Posada" },
      { id: 11, term: "しゅくはく", extra: "宿泊", answer: "Alojamiento" },
      {
        id: 12,
        term: "とまります、とまる",
        extra: "泊まる",
        answer: "Alojarse",
      },
      { id: 13, term: "しゅくだい", extra: "宿題", answer: "Tarea" },
      { id: 14, term: "だいめい", extra: "題名", answer: "Titulo" },
      { id: 15, term: "めいし", extra: "名刺", answer: "Tarjeta de negocio" },
      { id: 16, term: "めいじん", extra: "名人", answer: "Experto, Maestro" },
      { id: 17, term: "ゆうめい", extra: "有名", answer: "Famoso" },
      { id: 18, term: "なまえ", extra: "名前", answer: "Nombre" },
      { id: 19, term: "まえ", extra: "前", answer: "En frente de, Antes" },
      { id: 20, term: "ぜんじつ", extra: "前日", answer: "Dia anterior" },
      { id: 21, term: "いいます、いう", extra: "言う", answer: "Decir" },
      { id: 22, term: "ことば", extra: "言葉", answer: "Palabra" },
      { id: 23, term: "げんご", extra: "言語", answer: "Lenguaje, Idioma" },
      { id: 24, term: "はなします、はなす", extra: "話す", answer: "Hablar" },
      { id: 25, term: "かいわ", extra: "会話", answer: "Conversacion" },
      {
        id: 26,
        term: "さくぶん",
        extra: "作文",
        answer: "Composicion (escritura), Ensayo (escritura)",
      },
      {
        id: 27,
        term: "おくります、おくる",
        extra: "送る",
        answer: "Mandar algo, Enviar",
      },
      {
        id: 28,
        term: "おきます、おきる",
        extra: "起きる",
        answer: "Despertar, Levantarse",
      },
      { id: 29, term: "きりつ", extra: "起立", answer: "Ponerse de pie" },
      {
        id: 30,
        term: "ねます、ねる",
        extra: "寝る",
        answer: "Dormir, Acostarse",
      },
      { id: 31, term: "はしります、はしる", extra: "走る", answer: "Correr" },
      { id: 32, term: "そう", extra: "〜走", answer: "Carrera(deportes)" },
      {
        id: 33,
        term: "のります、のる",
        extra: "乗る",
        answer: "Subirse(a un tren, bus, avion, etc.)",
      },
      {
        id: 34,
        term: "じょうしゃ",
        extra: "乗車",
        answer: "Embarque(en Tren, Bus, etc.)",
      },
      { id: 35, term: "しよう", extra: "使用", answer: "Uso" },
      { id: 36, term: "どくしょ", extra: "読書", answer: "Lectura" },
      { id: 37, term: "ききます、きく", extra: "聞く", answer: "Escuchar" },
      { id: 38, term: "しんぶん", extra: "新聞", answer: "Diario(noticias)" },
      { id: 39, term: "じぶん", extra: "自分", answer: "Uno mismo" },
      { id: 40, term: "とき", extra: "時", answer: "Cuando, Tiempo" },
      { id: 41, term: "じ", extra: "時", answer: "Hora" },
      { id: 42, term: "わけます、わける", extra: "分ける", answer: "Dividir" },
      { id: 43, term: "のみます、のむ", extra: "飲む", answer: "Beber, Tomar" },
      { id: 44, term: "いんしょく", extra: "飲食", answer: "Comer y beber" },
      { id: 45, term: "あいだ", extra: "間", answer: "Espacio entre" },
      { id: 46, term: "わたし", extra: "私", answer: "Yo" },
      { id: 47, term: "しぶつ", extra: "私物", answer: "Objetos personales" },
      { id: 48, term: "どうぶつ", extra: "動物", answer: "Animal" },
      { id: 49, term: "うごきます、うごく", extra: "動く", answer: "Mover" },
    ],
  },
  {
    id: "9",
    name: "Clase 2 Kanji",
    termList: [
      {
        id: 0,
        term: "自己紹介",
        extra: "",
        answer: "じこしょうかい / Presentarse a si mismo",
      },
      {
        id: 1,
        term: "書き順",
        extra: "",
        answer: "かきじゅん / Orden de trazos",
      },
      {
        id: 2,
        term: "漢",
        extra: "",
        answer: "おとこ / Hombre de hombres, Macho, Tipo duro.",
      },
      { id: 3, term: "女子", extra: "", answer: "じょし / Mujer, Niña" },
      { id: 4, term: "男子", extra: "", answer: "だんし / Hombre, Niño" },
      { id: 5, term: "文字", extra: "", answer: "もじ / Letra" },
      { id: 6, term: "文", extra: "", answer: "ぶん / Oracion" },
      {
        id: 7,
        term: "文章",
        extra: "",
        answer: "ぶんしょう / Ensayo（escrito）, Oraciones",
      },
      { id: 8, term: "文化", extra: "", answer: "ぶんか / Cultura" },
      { id: 9, term: "工学", extra: "", answer: "こうがく / Ingenieria" },
      { id: 10, term: "宿", extra: "", answer: "やど / Alojamiento, Posada" },
      { id: 11, term: "宿泊", extra: "", answer: "しゅくはく / Alojamiento" },
      {
        id: 12,
        term: "泊まる",
        extra: "",
        answer: "とまります、とまる / Alojarse",
      },
      { id: 13, term: "宿題", extra: "", answer: "しゅくだい / Tarea" },
      { id: 14, term: "題名", extra: "", answer: "だいめい / Titulo" },
      {
        id: 15,
        term: "名刺",
        extra: "",
        answer: "めいし / Tarjeta de negocio",
      },
      {
        id: 16,
        term: "名人",
        extra: "",
        answer: "めいじん / Experto, Maestro",
      },
      { id: 17, term: "有名", extra: "", answer: "ゆうめい / Famoso" },
      { id: 18, term: "名前", extra: "", answer: "なまえ / Nombre" },
      { id: 19, term: "前", extra: "", answer: "まえ / En frente de, Antes" },
      { id: 20, term: "前日", extra: "", answer: "ぜんじつ / Dia anterior" },
      { id: 21, term: "言う", extra: "", answer: "いいます、いう / Decir" },
      { id: 22, term: "言葉", extra: "", answer: "ことば / Palabra" },
      { id: 23, term: "言語", extra: "", answer: "げんご / Lenguaje, Idioma" },
      {
        id: 24,
        term: "話す",
        extra: "",
        answer: "はなします、はなす / Hablar",
      },
      { id: 25, term: "会話", extra: "", answer: "かいわ / Conversacion" },
      {
        id: 26,
        term: "作文",
        extra: "",
        answer: "さくぶん / Composicion (escritura)",
      },
      {
        id: 27,
        term: "送る",
        extra: "",
        answer: "おくります、おくる / Mandar algo, Enviar",
      },
      {
        id: 28,
        term: "起きる",
        extra: "",
        answer: "おきます、おきる / Despertar, Levantarse",
      },
      { id: 29, term: "起立", extra: "", answer: "きりつ / Ponerse de pie" },
      {
        id: 30,
        term: "寝る",
        extra: "",
        answer: "ねます、ねる / Dormir, Acostarse",
      },
      {
        id: 31,
        term: "走る",
        extra: "",
        answer: "はしります、はしる / Correr",
      },
      { id: 32, term: "〜走", extra: "", answer: "そう / Carrera(deportes)" },
      {
        id: 33,
        term: "乗る",
        extra: "",
        answer: "のります、のる / Subirse(a un tren, bus, avion, etc.)",
      },
      {
        id: 34,
        term: "乗車",
        extra: "",
        answer: "じょうしゃ / Embarque(en Tren, Bus, etc.)",
      },
      { id: 35, term: "使用", extra: "", answer: "しよう / Uso" },
      { id: 36, term: "読書", extra: "", answer: "どくしょ / Lectura" },
      { id: 37, term: "聞く", extra: "", answer: "ききます、きく / Escuchar" },
      {
        id: 38,
        term: "新聞",
        extra: "",
        answer: "しんぶん / Diario(noticias)",
      },
      { id: 39, term: "自分", extra: "", answer: "じぶん / Uno mismo" },
      { id: 40, term: "時", extra: "", answer: "とき / Cuando, Tiempo" },
      { id: 41, term: "時", extra: "", answer: "じ / Hora" },
      {
        id: 42,
        term: "分ける",
        extra: "",
        answer: "わけます、わける / Dividir",
      },
      {
        id: 43,
        term: "飲む",
        extra: "",
        answer: "のみます、のむ / Beber, Tomar",
      },
      { id: 44, term: "飲食", extra: "", answer: "いんしょく / Comer y beber" },
      { id: 45, term: "間", extra: "", answer: "あいだ / Espacio entre" },
      { id: 46, term: "私", extra: "", answer: "わたし / Yo" },
      {
        id: 47,
        term: "私物",
        extra: "",
        answer: "しぶつ / Objetos personales",
      },
      { id: 48, term: "動物", extra: "", answer: "どうぶつ / Animal" },
      { id: 49, term: "動く", extra: "", answer: "うごきます、うごく / Mover" },
    ],
  },
  {
    id: "10",
    name: "Clase 3",
    termList: [
      { id: 0, term: "おんせい", extra: "音声", answer: "Sonido de voz" },
      { id: 32, term: "こえ", extra: "声", answer: "Voz" },
      { id: 1, term: "しんぱい", extra: "心配", answer: "Preocupacion" },
      { id: 2, term: "ねんれい", extra: "年齢", answer: "Edad" },
      { id: 3, term: "あまい", extra: "甘い", answer: "Dulce(sabor)" },
      { id: 4, term: "ほん", extra: "本", answer: "Libro" },
      { id: 5, term: "しごと", extra: "仕事", answer: "Trabajo" },
      { id: 6, term: "むし", extra: "虫", answer: "Insecto" },
      { id: 7, term: "むし", extra: "無視", answer: "Ignoracion*" },
      { id: 8, term: "きらい", extra: "嫌い", answer: "(algo) Odiado" },
      { id: 9, term: "なま", extra: "生", answer: "Natural, Crudo" },
      {
        id: 10,
        term: "なましぼり",
        extra: "生絞り",
        answer: "Recien exprimido",
      },
      { id: 11, term: "うすい", extra: "薄い", answer: "Aguado" },
      { id: 12, term: "こい", extra: "濃い", answer: "Concentrado" },
      { id: 13, term: "ま", extra: "間", answer: "Tiempo, Pausa" },
      { id: 31, term: "〜のあいだ", extra: "〜の間", answer: "Durante" },
      { id: 14, term: "きる", extra: "切る", answer: "Cortar" },
      { id: 15, term: "そうしん", extra: "送信", answer: "Envio correo" },
      {
        id: 16,
        term: "わすれます、わすれる",
        extra: "忘れる",
        answer: "Olvidar",
      },
      {
        id: 17,
        term: "おぼえます、おぼえる",
        extra: "覚える",
        answer: "Memorizar",
      },
      {
        id: 18,
        term: "けんがく",
        extra: "見学",
        answer: "Aprender por la vista",
      },
      { id: 19, term: "あさ", extra: "朝", answer: "Mañana(hora del dia)" },
      { id: 20, term: "あさごはん", extra: "朝ごはん", answer: "Desayuno" },
      {
        id: 21,
        term: "ちょうしょく",
        extra: "朝食",
        answer: "Desayuno (formal)",
      },
      { id: 22, term: "ひる", extra: "昼", answer: "Mediodia" },
      { id: 23, term: "ひるごはん", extra: "昼ごはん", answer: "Almuerzo" },
      {
        id: 24,
        term: "ちゅうしょく",
        extra: "昼食",
        answer: "Almuerzo (formal)",
      },
      { id: 33, term: "ばんごはん", extra: "晩ごはん", answer: "Cena" },
      { id: 34, term: "ゆうしょく", extra: "夕食", answer: "Cena (formal)" },
      {
        id: 25,
        term: "おわります、おわる",
        extra: "終わる",
        answer: "Terminar(intransitivo)",
      },
      {
        id: 26,
        term: "おえます、おえる",
        extra: "終える",
        answer: "Terminar(transitivo)",
      },
      {
        id: 27,
        term: "つながります、つながる",
        extra: "繋がる",
        answer: "Conectar(Intransitivo)",
      },
      {
        id: 28,
        term: "つなげます、つなげる",
        extra: "繋げる",
        answer: "Conectar(transitivo)",
      },
      { id: 29, term: "よてい", extra: "予定", answer: "Plan" },
      { id: 30, term: "おなじ", extra: "同じ", answer: "Igual, Identico" },
    ],
  },
  {
    id: "11",
    name: "Clase 3 Kanji",
    termList: [
      { id: 0, term: "音声", extra: "", answer: "おんせい / Sonido de voz" },
      { id: 32, term: "声", extra: "", answer: "こえ / Voz" },
      { id: 1, term: "心配", extra: "", answer: "しんぱい / Preocupacion" },
      { id: 2, term: "年齢", extra: "", answer: "ねんれい / Edad" },
      { id: 3, term: "甘い", extra: "", answer: "あまい / Dulce(sabor)" },
      { id: 4, term: "本", extra: "", answer: "ほん / Libro" },
      { id: 5, term: "仕事", extra: "", answer: "しごと / Trabajo" },
      { id: 6, term: "虫", extra: "", answer: "むし / Insecto" },
      { id: 7, term: "無視", extra: "", answer: "むし / Ignoracion*" },
      { id: 8, term: "嫌い", extra: "", answer: "きらい / (algo) Odiado" },
      { id: 9, term: "生", extra: "", answer: "なま / Natural, Crudo" },
      {
        id: 10,
        term: "生絞り",
        extra: "",
        answer: "なましぼり / Recien exprimido",
      },
      { id: 11, term: "薄い", extra: "", answer: "うすい / Aguado" },
      { id: 12, term: "濃い", extra: "", answer: "こい / Concentrado" },
      { id: 13, term: "間", extra: "", answer: "ま / Tiempo, Pausa" },
      { id: 31, term: "〜の間", extra: "", answer: "〜のあいだ / Durante" },
      { id: 14, term: "切る", extra: "", answer: "きる / Cortar" },
      { id: 15, term: "送信", extra: "", answer: "そうしん / Envio correo" },
      {
        id: 16,
        term: "忘れる",
        extra: "",
        answer: "わすれます、わすれる / Olvidar",
      },
      {
        id: 17,
        term: "覚える",
        extra: "",
        answer: "おぼえます、おぼえる / Memorizar",
      },
      {
        id: 18,
        term: "見学",
        extra: "",
        answer: "けんがく / Aprender por la vista",
      },
      { id: 19, term: "朝", extra: "", answer: "あさ / Mañana(hora del dia)" },
      { id: 20, term: "朝ごはん", extra: "", answer: "あさごはん / Desayuno" },
      {
        id: 21,
        term: "朝食",
        extra: "",
        answer: "ちょうしょく / Desayuno (formal)",
      },
      { id: 22, term: "昼", extra: "", answer: "ひる / Mediodia" },
      { id: 23, term: "昼ごはん", extra: "", answer: "ひるごはん / Almuerzo" },
      {
        id: 24,
        term: "昼食",
        extra: "",
        answer: "ちゅうしょく / Almuerzo (formal)",
      },
      { id: 33, term: "晩ごはん", extra: "", answer: "ばんごはん / Cena" },
      { id: 34, term: "夕食", extra: "", answer: "ゆうしょく / Cena (formal)" },
      {
        id: 25,
        term: "終わる",
        extra: "",
        answer: "おわります、おわる / Terminar(intransitivo)",
      },
      {
        id: 26,
        term: "終える",
        extra: "",
        answer: "おえます、おえる / Terminar(transitivo)",
      },
      {
        id: 27,
        term: "繋がる",
        extra: "",
        answer: "つながります、つながる / Conectar(Intransitivo)",
      },
      {
        id: 28,
        term: "繋げる",
        extra: "",
        answer: "つなげます、つなげる / Conectar(transitivo)",
      },
      { id: 29, term: "予定", extra: "", answer: "よてい / Plan" },
      { id: 30, term: "同じ", extra: "", answer: "おなじ / Igual, Identico" },
    ],
  },
  {
    id: "12",
    name: "Clase 4",
    termList: [
      { id: 0, term: "おもいます、おもう", extra: "思う", answer: "Pensar" },
      { id: 1, term: "かえります、かえる", extra: "帰る", answer: "Regresar" },
      { id: 2, term: "もどります、もどる", extra: "戻る", answer: "Regresar" },
      {
        id: 3,
        term: "つきます、つく",
        extra: "付く",
        answer: "Prenderse(la luz), Ser puesto, (ambos intransitivo)",
      },
      {
        id: 4,
        term: "つけます、つける",
        extra: "付ける",
        answer: "Prender(la luz), Poner (ambos transitivo)",
      },
      {
        id: 5,
        term: "すっかり",
        extra: "",
        answer: "Todo ello, Sin dejar residuo",
      },
      { id: 6, term: "せんたく", extra: "選択", answer: "Seleccion, Eleccion" },
      {
        id: 7,
        term: "せんたくじゅぎょう",
        extra: "選択授業",
        answer: "Clase optativa",
      },
      { id: 8, term: "せんたく", extra: "洗濯", answer: "Lavado de ropa" },
      { id: 9, term: "はる", extra: "春", answer: "Primavera" },
      {
        id: 10,
        term: "せいしゅん",
        extra: "青春",
        answer: "Memoria de juventud",
      },
      {
        id: 11,
        term: "そうしゅん",
        extra: "早春",
        answer: "Principios de la primavera",
      },
      { id: 12, term: "なつ", extra: "夏", answer: "Verano" },
      { id: 13, term: "れいか", extra: "冷夏", answer: "Verano helado" },
      {
        id: 14,
        term: "しょか",
        extra: "初夏",
        answer: "Principios del verano",
      },
      { id: 15, term: "あき", extra: "秋", answer: "Otoño" },
      {
        id: 16,
        term: "さくしゅう",
        extra: "昨秋",
        answer: "Otoño del año pasado",
      },
      { id: 17, term: "ばんしゅう", extra: "晩秋", answer: "Finales de otoño" },
      { id: 18, term: "ふゆ", extra: "冬", answer: "Invierno" },
      { id: 19, term: "だんとう", extra: "暖冬", answer: "Invierno calido" },
      { id: 20, term: "とうみん", extra: "冬眠", answer: "Hibernacion" },
      {
        id: 21,
        term: "さきます、さく",
        extra: "咲く",
        answer: "Florecer (intransitivo)",
      },
      { id: 22, term: "よる", extra: "夜", answer: "Noche" },
      {
        id: 23,
        term: "よるごはん",
        extra: "夜ご飯",
        answer: "Comida despues de la cena",
      },
      {
        id: 24,
        term: "やしょく",
        extra: "夜食",
        answer: "Comida despues de la cena (formal)",
      },
      { id: 25, term: "ゆうしょく", extra: "夕食", answer: "Cena (formal)" },
      { id: 26, term: "ばんめし", extra: "晩飯", answer: "Cena (informal)" },
      { id: 27, term: "いぬ", extra: "犬", answer: "Perro" },
      { id: 28, term: "ぼく", extra: "僕", answer: "Yo (informal)" },
      { id: 29, term: "は", extra: "歯", answer: "Diente" },
      {
        id: 30,
        term: "はみがき",
        extra: "歯磨き",
        answer: "Lavado de dientes",
      },
      { id: 31, term: "なか", extra: "仲", answer: "Relacion" },
      { id: 32, term: "なかなおり", extra: "仲直り", answer: "Reconciliacion" },
      { id: 33, term: "にく", extra: "肉", answer: "Carne" },
      { id: 34, term: "じゃがいも", extra: "じゃが芋", answer: "Patata" },
      {
        id: 35,
        term: "にくじゃが",
        extra: "肉じゃが",
        answer: "Guiso de carne y papas",
      },
      { id: 36, term: "ほうちょう", extra: "包丁", answer: "Cuchillo cocina" },
      { id: 37, term: "ナイフ", extra: "", answer: "Cuchillo" },
      { id: 38, term: "にんじん", extra: "人参", answer: "Zanahoria" },
      { id: 39, term: "たまねぎ", extra: "玉ねぎ", answer: "Cebolla" },
      { id: 40, term: "あな", extra: "穴", answer: "Hoyo, Agujero, Hueco" },
      { id: 41, term: "まないた", extra: "まな板", answer: "Tabla de cortar" },
      { id: 42, term: "やさい", extra: "野菜", answer: "Verduras" },
      {
        id: 43,
        term: "にます、にる",
        extra: "煮る",
        answer: "Cocer a fuego lento",
      },
      { id: 44, term: "あじ", extra: "味", answer: "Sabor" },
      {
        id: 45,
        term: "ようちえんじ",
        extra: "幼稚園児",
        answer: "niño de kinder",
      },
      { id: 46, term: "かふん", extra: "花粉", answer: "Polen" },
      {
        id: 47,
        term: "かふんしょう",
        extra: "花粉症",
        answer: "Alergia al polen",
      },
      { id: 48, term: "のうえん", extra: "農園", answer: "Granja, Plantacion" },
      {
        id: 49,
        term: "しぜんかい",
        extra: "自然界",
        answer: "Mundo de la naturaleza",
      },
      { id: 50, term: "みつばち、ミツバチ", extra: "蜜蜂", answer: "Abeja" },
      { id: 51, term: "み", extra: "実", answer: "Fruto y semilla de plantas" },
      { id: 52, term: "くだもの", extra: "果物", answer: "Fruta" },
      {
        id: 53,
        term: "えがお",
        extra: "笑顔",
        answer: "Sonrisa, Cara sonriente",
      },
      { id: 54, term: "みせいねん", extra: "未成年", answer: "Menor de edad" },
      { id: 55, term: "せいじん", extra: "成人", answer: "Mayor de edad" },
      {
        id: 56,
        term: "はんたい",
        extra: "反対",
        answer: "Opuesto, Inverso、Oponerse a una opinion",
      },
      {
        id: 57,
        term: "さんせい",
        extra: "賛成",
        answer: "Estar de acuerdo con la opinion de otra persona",
      },
      { id: 58, term: "ぎむ", extra: "義務", answer: "Obligacion" },
      { id: 59, term: "み", extra: "身", answer: "Cuerpo" },
      {
        id: 60,
        term: "みのまわり",
        extra: "身の回り",
        answer:
          "Cosas que ocurren en la vida cotidiana, Objeto puesto o que se tenga cerca a diario.",
      },
      {
        id: 61,
        term: "ざいさん",
        extra: "財産",
        answer: "Propiedad, Los bienes, Riqueza",
      },
      { id: 62, term: "ちしき", extra: "知識", answer: "Conocimientos" },
      {
        id: 63,
        term: "しんけん",
        extra: "親権",
        answer: "Responsabilidades parentales, Patria potestad",
      },
      {
        id: 64,
        term: "きょうどうしんけん",
        extra: "共同親権",
        answer: "Custodia compartida",
      },
      {
        id: 65,
        term: "たんどくしんけん",
        extra: "単独親権",
        answer: "Custodia exclusiva",
      },
      { id: 66, term: "おや", extra: "親", answer: "Papa/Mama/Padres" },
      { id: 67, term: "りょうしん", extra: "両親", answer: "Padres" },
      { id: 68, term: "おせわ", extra: "お世話", answer: "Ayuda, Cuidado" },
      {
        id: 69,
        term: "かんり",
        extra: "管理",
        answer: "Administracion, Gestion",
      },
      { id: 70, term: "～にかわる", extra: "～に代わる", answer: "En vez de " },
      { id: 71, term: "さまざま", extra: "様々", answer: "Diverso, Varios" },
      { id: 72, term: "ほうりつ", extra: "法律", answer: "Ley" },
      { id: 73, term: "みのぽう", extra: "民法", answer: "Ley civil" },
      { id: 74, term: "けっこん", extra: "結婚", answer: "Matrimonio" },
      { id: 75, term: "りこん", extra: "離婚", answer: "Divorcio" },
      {
        id: 76,
        term: "さだめます、さだめる",
        extra: "定める",
        answer: "Decidir",
      },
      {
        id: 77,
        term: "だいり",
        extra: "代理",
        answer:
          "Encargarse de asuntos (especialmente deberes) en nombre de otra persona, Representativo, Proxy, Subrogado",
      },
    ],
  },
  {
    id: "13",
    name: "Clase 4 Kanji",
    termList: [
      { id: 0, term: "思う", extra: "", answer: "おもいます、おもう / Pensar" },
      {
        id: 1,
        term: "帰る",
        extra: "",
        answer: "かえります、かえる / Regresar",
      },
      {
        id: 2,
        term: "戻る",
        extra: "",
        answer: "もどります、もどる / Regresar",
      },
      {
        id: 3,
        term: "付く",
        extra: "",
        answer:
          "つきます、つく / Prenderse(la luz), Ser puesto, (ambos intransitivo)",
      },
      {
        id: 4,
        term: "付ける",
        extra: "",
        answer: "つけます、つける / Prender(la luz), Poner (ambos transitivo)",
      },
      {
        id: 5,
        term: "選択",
        extra: "",
        answer: "せんたく / Seleccion, Eleccion",
      },
      {
        id: 6,
        term: "選択授業",
        extra: "",
        answer: "せんたくじゅぎょう / Clase optativa",
      },
      { id: 7, term: "洗濯", extra: "", answer: "せんたく / Lavado de ropa" },
      { id: 8, term: "春", extra: "", answer: "はる / Primavera" },
      {
        id: 9,
        term: "青春",
        extra: "",
        answer: "せいしゅん / Memoria de juventud",
      },
      {
        id: 10,
        term: "早春",
        extra: "",
        answer: "そうしゅん / Principios de la primavera",
      },
      { id: 11, term: "夏", extra: "", answer: "なつ / Verano" },
      { id: 12, term: "冷夏", extra: "", answer: "れいか / Verano helado" },
      {
        id: 13,
        term: "初夏",
        extra: "",
        answer: "しょか / Principios del verano",
      },
      { id: 14, term: "秋", extra: "", answer: "あき / Otoño" },
      {
        id: 15,
        term: "昨秋",
        extra: "",
        answer: "さくしゅう / Otoño del año pasado",
      },
      {
        id: 16,
        term: "晩秋",
        extra: "",
        answer: "ばんしゅう / Finales de otoño",
      },
      { id: 17, term: "冬", extra: "", answer: "ふゆ / Invierno" },
      { id: 18, term: "暖冬", extra: "", answer: "だんとう / Invierno calido" },
      { id: 19, term: "冬眠", extra: "", answer: "とうみん / Hibernacion" },
      {
        id: 20,
        term: "咲く",
        extra: "",
        answer: "さきます、さく / Florecer (intransitivo)",
      },
      { id: 21, term: "夜", extra: "", answer: "よる / Noche" },
      {
        id: 22,
        term: "夜ご飯",
        extra: "",
        answer: "よるごはん / Comida despues de la cena",
      },
      {
        id: 23,
        term: "夜食",
        extra: "",
        answer: "やしょく / Comida despues de la cena (formal)",
      },
      { id: 24, term: "夕食", extra: "", answer: "ゆうしょく / Cena (formal)" },
      { id: 25, term: "晩飯", extra: "", answer: "ばんめし / Cena (informal)" },
      { id: 26, term: "犬", extra: "", answer: "いぬ / Perro" },
      { id: 27, term: "僕", extra: "", answer: "ぼく / Yo (informal)" },
      { id: 28, term: "歯", extra: "", answer: "は / Diente" },
      {
        id: 29,
        term: "歯磨き",
        extra: "",
        answer: "はみがき / Lavado de dientes",
      },
      { id: 30, term: "仲", extra: "", answer: "なか / Relacion" },
      {
        id: 31,
        term: "仲直り",
        extra: "",
        answer: "なかなおり / Reconciliacion",
      },
      { id: 32, term: "肉", extra: "", answer: "にく / Carne" },
      { id: 33, term: "じゃが芋", extra: "", answer: "じゃがいも / Patata" },
      {
        id: 34,
        term: "肉じゃが",
        extra: "",
        answer: "にくじゃが / Guiso de carne y papas",
      },
      {
        id: 35,
        term: "包丁",
        extra: "",
        answer: "ほうちょう / Cuchillo cocina",
      },
      { id: 36, term: "人参", extra: "", answer: "にんじん / Zanahoria" },
      { id: 37, term: "玉ねぎ", extra: "", answer: "たまねぎ / Cebolla" },
      { id: 38, term: "穴", extra: "", answer: "あな / Hoyo, Agujero, Hueco" },
      {
        id: 39,
        term: "まな板",
        extra: "",
        answer: "まないた / Tabla de cortar",
      },
      { id: 40, term: "野菜", extra: "", answer: "やさい / Verduras" },
      {
        id: 41,
        term: "煮る",
        extra: "",
        answer: "にます、にる / Cocer a fuego lento",
      },
      { id: 42, term: "味", extra: "", answer: "あじ / Sabor" },
      {
        id: 43,
        term: "幼稚園児",
        extra: "",
        answer: "ようちえんじ / niño de kinder",
      },
      { id: 44, term: "花粉", extra: "", answer: "かふん / Polen" },
      {
        id: 45,
        term: "花粉症",
        extra: "",
        answer: "かふんしょう / Alergia al polen",
      },
      {
        id: 46,
        term: "農園",
        extra: "",
        answer: "のうえん / Granja, Plantacion",
      },
      {
        id: 47,
        term: "自然界",
        extra: "",
        answer: "しぜんかい / Mundo de la naturaleza",
      },
      { id: 48, term: "蜜蜂", extra: "", answer: "みつばち、ミツバチ / Abeja" },
      {
        id: 49,
        term: "実",
        extra: "",
        answer: "み / Fruto y semilla de plantas",
      },
      { id: 50, term: "果物", extra: "", answer: "くだもの / Fruta" },
      {
        id: 51,
        term: "笑顔",
        extra: "",
        answer: "えがお / Sonrisa, Cara sonriente",
      },
      {
        id: 52,
        term: "未成年",
        extra: "",
        answer: "みせいねん / Menor de edad",
      },
      { id: 53, term: "成人", extra: "", answer: "せいじん / Mayor de edad" },
      {
        id: 54,
        term: "反対",
        extra: "",
        answer: "はんたい / Opuesto, Inverso、Oponerse a una opinion",
      },
      {
        id: 55,
        term: "賛成",
        extra: "",
        answer: "さんせい / Estar de acuerdo con la opinion de otra persona",
      },
      { id: 56, term: "義務", extra: "", answer: "ぎむ / Obligacion" },
      { id: 57, term: "身", extra: "", answer: "み / Cuerpo" },
      {
        id: 58,
        term: "身の回り",
        extra: "",
        answer:
          "みのまわり / Cosas que ocurren en la vida cotidiana, Objeto puesto o que se tenga cerca a diario.",
      },
      {
        id: 59,
        term: "財産",
        extra: "",
        answer: "ざいさん / Propiedad, Los bienes, Riqueza",
      },
      { id: 60, term: "知識", extra: "", answer: "ちしき / Conocimientos" },
      {
        id: 61,
        term: "親権",
        extra: "",
        answer: "しんけん / Responsabilidades parentales, Patria potestad",
      },
      {
        id: 62,
        term: "共同親権",
        extra: "",
        answer: "きょうどうしんけん / Custodia compartida",
      },
      {
        id: 63,
        term: "単独親権",
        extra: "",
        answer: "たんどくしんけん / Custodia exclusiva",
      },
      { id: 64, term: "親", extra: "", answer: "おや / Papa/Mama/Padres" },
      { id: 65, term: "両親", extra: "", answer: "りょうしん / Padres" },
      { id: 66, term: "お世話", extra: "", answer: "おせわ / Ayuda, Cuidado" },
      {
        id: 67,
        term: "管理",
        extra: "",
        answer: "かんり / Administracion, Gestion",
      },
      {
        id: 68,
        term: "～に代わる",
        extra: "",
        answer: "～にかわる / En vez de ",
      },
      { id: 69, term: "様々", extra: "", answer: "さまざま / Diverso, Varios" },
      { id: 70, term: "法律", extra: "", answer: "ほうりつ / Ley" },
      { id: 71, term: "民法", extra: "", answer: "みのぽう / Ley civil" },
      { id: 72, term: "結婚", extra: "", answer: "けっこん / Matrimonio" },
      { id: 73, term: "離婚", extra: "", answer: "りこん / Divorcio" },
      {
        id: 74,
        term: "定める",
        extra: "",
        answer: "さだめます、さだめる / Decidir",
      },
      {
        id: 75,
        term: "代理",
        extra: "",
        answer:
          "だいり / Encargarse de asuntos (especialmente deberes) en nombre de otra persona, Representativo, Proxy, Subrogado",
      },
    ],
  },
];

export { lectures, options };

//el localstorage es un objeto que en basado en keys guarda objetos
let local = {
  0: { 0: "learned", 1: "learning", 2: "", lastCheckout: "4/11/23" },
  1: { 0: "learned", 1: "learning", 2: "", lastCheckout: "No Checkout" },
};
